from webscrapping.manager_data.requests_site import get_data
from webscrapping.manager_data.write_json_file import create_json
from webscrapping.manager_data.manager_config_sites import load_file_config,add_new_config
from webscrapping.manager_data.read_json_file import read_json
from webscrapping.manager_data.scan_folder import get_all_files